// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VisualThreading
{
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string VisualThreadingString = "46a432ab-b925-4851-a214-65069de24b60";
        public static Guid VisualThreading = new Guid(VisualThreadingString);
        public const string RadialWindowString = "0ea6b182-db3a-4f77-abf4-492c7b31036b";
        public static Guid RadialMenu = new Guid(RadialWindowString);
        public const string BuildingWindowString = "6a0155f8-b16a-4fba-90bb-8c9fab68de1b";
        public static Guid BuildingWindow = new Guid(BuildingWindowString);
        public const string PreviewWindowString = "8d4fca2b-a66b-485a-a01f-58a3b98aa35e";
        public static Guid PreviewWindow = new Guid(PreviewWindowString);


    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int OpenRadialMenu = 0x0100;
        public const int OpenCommandPreview = 0x0101;
        public const int OpenBuildingWindow = 0x0102;
    }
}