// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VisualThreading
{
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string VisualThreadingString = "fb0f5ed1-f75d-4774-a7f9-5a3a7d612e5d";
        public static Guid VisualThreading = new Guid(VisualThreadingString);
        public const string RadialWindowString = "34b9ebb5-2c75-4bef-a755-39d77e165ecc";
        public static Guid RadialMenu = new Guid(RadialWindowString);
        public const string BuildingWindowString = "3056e2ec-342f-4817-8eeb-eddadeaf2432";
        public static Guid BuildingWindow = new Guid(BuildingWindowString);
        public const string PreviewWindowString = "43d0085b-8358-4aa6-98b2-c831523cefbc";
        public static Guid PreviewWindow = new Guid(PreviewWindowString);


    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int OpenRadialMenu = 0x0100;
        public const int OpenCommandPreview = 0x0101;
        public const int OpenBuildingWindow = 0x0102;
    }
}