// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VisualThreading
{
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string VisualThreadingString = "46a432ab-b925-4851-a214-65069de24b60";
        public static Guid VisualThreading = new Guid(VisualThreadingString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int OpenRadialMenu = 0x0100;
        public const int OpenCommandPreview = 0x0101;
        public const int OpenBuildingWindow = 0x0102;
    }
}