// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VisualNav
{
    internal sealed partial class Vsix
    {
        public const string Id = "VisualNav.e558fd3f-b919-4f5d-8d91-56d337f74a73";
        public const string Name = "VisualNav";
        public const string Description = @"Provides new metaphor's to navigate components in building an app!";
        public const string Language = "en-US";
        public const string Version = "1.3";
        public const string Author = "UCL FacialNav for Visual Studio";
        public const string Tags = "";
    }
}
