// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VisualNav
{
    internal sealed partial class Vsix
    {
        public const string Id = "VisualNav.d1030a34-cc66-4021-8ed2-568d8b857e1b";
        public const string Name = "VisualNav";
        public const string Description = @"Provides new metaphor's to navigate components in building an app!";
        public const string Language = "en-US";
        public const string Version = "1.2";
        public const string Author = "UCL FacialNav for Visual Studio";
        public const string Tags = "";
    }
}
