// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VisualNav
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string VisualNavString = "c739d2d9-3f91-4f11-b770-a7afe26acf73";
        public static Guid VisualNav = new Guid(VisualNavString);

        public const string RadialWindowString = "7cc719fc-b24f-42fc-b5c2-a7bc93c64e21";
        public static Guid RadialWindow = new Guid(RadialWindowString);

        public const string BuildingWindowString = "2afd90c3-931f-4964-bbbc-005bc11950e9";
        public static Guid BuildingWindow = new Guid(BuildingWindowString);

        public const string PreviewWindowString = "8703a46e-2c71-4641-bfe2-73faafd33254";
        public static Guid PreviewWindow = new Guid(PreviewWindowString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int ToolGroup = 0x0002;
        public const int OpenRadialMenu = 0x0100;
        public const int OpenCommandPreview = 0x0101;
        public const int OpenBuildingWindow = 0x0102;
        public const int OpenAllWindows = 0x0103;
        public const int Maximize = 0x0104;
        public const int Minimize = 0x0105;
        public const int ZoomIn = 0x0106;
        public const int ZoomOut = 0x0107;
        public const int ResetZoom = 0x0108;
        public const int Insert = 0x0109;
        public const int Clip = 0x0110;
    }
}